title: "How to Q: The Amazon Q mentor"
description: All things on How and Why to use Amazon Q
remote_theme: just-the-docs/just-the-docs

# Enable copy code button
enable_copy_code_button: true

# Color scheme
color_scheme: dark

# External navigation
nav_external_links:
- title: Amazon Q home
  url: https://aws.amazon.com/q/
  hide_icon: false
- title: Amazon Q Developer change log
  url: https://aws.amazon.com/developer/generative-ai/amazon-q/change-log/

# Search settings
search_enabled: true
search:
  heading_level: 3
  previews: 3
  preview_words_before: 5
  preview_words_after: 10

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"
