title: "How to Q"
description: How and Why to use Amazon Q
remote_theme: just-the-docs/just-the-docs

# Enable copy code button
enable_copy_code_button: true

# Color scheme
color_scheme: aws

# External navigation links
nav_external_links:
  - title: Contribute
    url: https://github.com/mhausenblas/howtoq.help/discussions
    hide_icon: false

# Search settings
search_enabled: true
search:
  heading_level: 3
  previews: 3
  preview_words_before: 5
  preview_words_after: 10

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: yellow
  info:
    title: Info
    color: green
